// 
// This source code was auto-generated by bobflux-gen, Version=0.14.1.
// Don't modify this file but re-generate it by bobflux-gen.
// Bobflux-gen - https://www.npmjs.com/package/bobflux-gen
//

import * as s from './state';
import * as f from 'bobflux';
import * as state from './todo/state';

export * from './state';

export const rootKey = f.rootCursor.key;

export const rootCursor: f.ICursor<s.IApplicationState> = {
    key: ''
};

export default rootCursor;

export const todosCursor: f.ICursor<state.ITodosState> = {
    key: 'todos'
};
